server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/ms_email
spring.datasource.username=ALTERAR PARA O SEU USUÁRIO MYSQL
spring.datasource.password=ALTERAR PARA A SUA SENHA
spring.jpa.hibernate.ddl-auto=update
spring.application.name=email
spring.rabbitmq.addresses=ALTERAR PARA O SEU ENDEREÇO DO RABBITMQ
broker.queue.email.name=default.email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ALTERAR PARA O SEU EMAIL
spring.mail.password=ALTERAR PARA A SUA SENHA
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true